### ISSUE TITLE
How to send data in batch

### ISSUE THREAD

**Issue by ankit-matellio** [shubinmi/salesforce-bulk-api#10]
Hi,

As salesforce suggests to send data to the bulk api in batches of maximum of 10000 records mentioned in this URL:
https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_bulkapi.htm

I read your documentation but didn't find how to send data in batches of 10000 records. I am trying to sending a bunch of 20000, 50000 or even 1Lac record in a single shot using addBatchToJob function. But it always gives error regarding the batch: Batch ***** return failed. Please suggest how to send large data(more than 10000 records) through your API? 

I think, we can break the record into bunch of 10000 records and send them in addBatchToJob in a single job through a loop, is this correct?

**Comment by shubinmi** [comment]
> I think, we can break the record into bunch of 10000 records and send them in addBatchToJob in a single job through a loop, is this correct?

I believe so.
Try the way like following
`$insertJob = (new JobSFApiService($params))
    ->initJob($jobRequest);`
`for ($i=0; i < ceil(count($allDataArray)/10000); $i++) {`
`$data= array_slice($allDataArray, i*10000, 10000);`
   ` $insertJob->addBatchToJob($data);`
`}`
   ` $insertJob->closeJob();`

**Comment by ankit-matellio** [comment]
Thank you for response. Really appreciate.

Yes, i followed the same way you suggested and it seems to be working. 

Can you please suggest, how can we send data in serial mode instead of parallel mode? I didn't find anything regarding this in documentation,
