### ISSUE TITLE
Batch status is the first result vs final.

### ISSUE THREAD

**Issue by wiretail** [shubinmi/salesforce-bulk-api#2]
First, thank you for creating a modern, stand-alone PHP bulk API library.  I looked for similar last year...and was very happy to find this recently!

I'm currently only using the bulk API for large SELECT queries (with seems the less used use-case for the bulk API) and noticed an issue in JobSFApiService->waitingForComplete() when it has to wait.   Since $batches is assigned at the end of the wait recursion in reverse order, the first $batches result is what is saved at completion.  So the net effect is that the status after completion when a wait is required will be state "InProgress" and 0 records processed.

Should replicate on any query long enough to require waiting.  I fixed it quickly for my purposes like this this:

https://github.com/rgreer4/salesforce-bulk-api/commit/7cad13b5b636f89bdf0769a2d317fde4d4df9823

...however I didn't want to just send a pull request for that, as I don't really know how it might interact with UPDATE/INSERTs or other parts I don't use, if something else relies on that ordering of the batch updates.  (And it might be better to pass the latest batch through the recursion as a return value or something.)

Thanks again!

**Comment by shubinmi** [comment]
Rick, I really appreciate your contribution. So I added tests and applied your changes. Hope it will have some value for you.

**Comment by wiretail** [comment]
Awesome, thank you!  And thanks again for creating this.
