### ISSUE TITLE
Problem with the endpoint

### ISSUE THREAD

**Issue by luisalvarez** [shubinmi/salesforce-bulk-api#3]
This a great package and easy to implement just a tip and a question first:

In the test section the password and credencials that are set i hope no be yours that could be a vulnerability to you account.

The question is  i have a problem with: public static $endpoint = 'https://%s.salesforce.com/services/async/%s/job/%s/batch';

The endpoint property because my account domain no use that format, it uses prefix.my.salesforce.com.

I will think in way to config properly this but if you have a way o do it i wat for your feedback

**Comment by shubinmi** [comment]
Hi, Luis! I hope that inserting the next code before creating a job could be good solution for you
`\SalesforceBulkApi\api\BatchApiSF::$endpoint = 'https://%s.my.salesforce.com/services/async/%s/job/%s/batch';`

**Comment by luisalvarez** [comment]
Correct this the solution  !!! Thanks for the reply

2017-08-24 9:59 GMT-04:00 Maxim <notifications@github.com>:

**Comment by shubinmi** [comment]
👍  Thank you
