### ISSUE TITLE
Blank Error message if there was one.

### ISSUE THREAD

**Issue by bjsmasth** [shubinmi/salesforce-bulk-api#4]
Thank you for your great package.
I have trouble getting error messages. eg: if there was any error on query it returns me blank error messge: with 

```
$errors = $selectJob->initJob($jobRequest)
->addQueryBatchToJob($query)
->closeJob()
->waitingForComplete()
->getErrors();

if (!empty($errors)) {
                if(isset($errors[0]) && is_object($errors)) {$errors = $errors[0]->getErrorMessages();}
}
```

here $errors is a blank

**Comment by shubinmi** [comment]
Thank you for your contributions! I have added new property to BatchInfo, so now you will able to see error msg by `$errors[0]->getBatchInfo()->getStateMessage()`

**Comment by bjsmasth** [comment]
The latest commit for $errors[0]->getBatchInfo()->getStateMessage() is only available in master branch please make it available for tag

**Comment by shubinmi** [comment]
done 👍
