### ISSUE TITLE
500 error with JobSFApiService

### ISSUE THREAD

**Issue by chorton** [shubinmi/salesforce-bulk-api#8]
I'm using 1.1.9 of this package.  I'm getting a 500 error when calling the JobSFApiService.

I have verified the username, password, and token are correct (I use these for other connections to Salesforce, and those are working)

```
$sfApiParams = (new LoginParams)
    ->setUserName(config('salesforce.username'))
    ->setUserPass(config('salesforce.password'))
    ->setUserSecretToken(config('salesforce.token'))
    ->setAsEnterprise()
    ->setEndpointPrefixAsSandbox();

$sfApiUpsertJob = new JobSFApiService($sfApiParams);
```
I also tried it without `->setAsEnterprise()`

(I have removed the credentials from this response)

> ApiSalesforce request error: 500 ; Server error: `POST https:\/\/test.salesforce.com\/services\/Soap\/c\/39.0` resulted in a `500 Server Error` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?><soapenv:Envelope xmlns:soapenv=\"http:\/\/schemas.xmlsoap.org\/soap\/envelope\/\" xmlns: (truncated...)\n ; Request info: {\"uri\":{},\"method\":\"POST\",\"headers\":{\"Host\":[\"test.salesforce.com\"],\"Content-Type\":[\"text\\\/xml; charset=UTF8\"],\"SOAPAction\":[\"login\"]},\"body\":\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\" ?>\\n<env:Envelope xmlns:xsd=\\\"http:\\\/\\\/www.w3.org\\\/2001\\\/XMLSchema\\\" xmlns:xsi=\\\"http:\\\/\\\/www.w3.org\\\/2001\\\/XMLSchema-instance\\\" xmlns:env=\\\"http:\\\/\\\/schemas.xmlsoap.org\\\/soap\\\/envelope\\\/\\\">\\n  <env:Body>\\n    <n1:login xmlns:n1=\\\"urn:partner.soap.sforce.com\\\">\\n      <n1:username>myusernamehere<\\\/n1:username>\\n      <n1:password>mypasswordhere<\\\/n1:password>\\n    <\\\/n1:login>\\n  <\\\/env:Body>\\n<\\\/env:Envelope>\"}

**Comment by TallesPacheco** [comment]
I have the same problem

**Comment by davidjosephhayes** [comment]
I received this error when my username/password were null due to my `.env` file not loading properly. The following helped:

```
php artisan config:cache
php artisan config:clear
php artisan cache:clear
```

**Comment by davidjosephhayes** [comment]
Looks like password or tokens with an && ampersand can cause this. They are not properly escaped in the request XML.
```
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sf="urn:fault.partner.soap.sforce.com" xmlns:
xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Body>
    <soapenv:Fault>
      <faultcode>UNKNOWN_EXCEPTION</faultcode>
      <faultstring>UNKNOWN_EXCEPTION: The reference to entity &quot;myPasswordWithAnAmpersand&quot; must end with the &apos;;&apos; delimiter.</faultstring>
      <detail>
        <sf:UnexpectedErrorFault xsi:type="sf:UnexpectedErrorFault">
          <sf:exceptionCode>UNKNOWN_EXCEPTION</sf:exceptionCode>
          <sf:exceptionMessage>The reference to entity &quot;myPasswordWithAnAmpersand&quot; must end with the &apos;;&apos; delimiter.</sf:exceptionMessage>
       </sf:UnexpectedErrorFault>
     </detail>
   </soapenv:Fault>
  </soapenv:Body>
</soapenv:Envelope>
```

This change fixed the issue for me: https://github.com/shubinmi/salesforce-bulk-api/pull/13
